name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: git clone https://github.com/gek64/gek.git
    - run: curl -LOJ https://github.com/gek64/build-apps-scripts/raw/main/gobuilder.sh
    - run: ln -s ${{ github.workspace }}/gek ../gek
    - run: bash gobuilder.sh --all
    - run: ls .. -R -las
