name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: cd ${{ github.workspace }}
    - run: cd ..
    - run: git clone https://github.com/gek64/gek.git
    - run: ls /home/runner/work/WakeOnLAN
    - run: cd ${{ github.workspace }}
    - run: go -v
