name: Go Build and Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'LICENSE'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - run: git clone https://github.com/gek64/gek.git
    - run: curl -LOJ https://github.com/gek64/build-apps-scripts/raw/main/gobuilder.sh
    - run: ln -s ${{ github.workspace }}/gek ../gek
    - run: bash gobuilder.sh --os linux --arch amd64
    - run: ls .. -R -las
    - run: git push --delete origin latest
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"
        tag: 'latest'
        token: ${{ secrets.GITHUB_TOKEN }}
