name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: git clone https://github.com/gek64/gek.git
    - run: ln -s ./gek ../gek
    - run: ls .. -R -las
    - run: go build
